export const FETCH_ALL_TODO = "FETCH_ALL_TODO";
export const FETCH_ALL_TODO_SUCCESS = "FETCH_ALL_TODO_SUCCESS";
export const FETCH_ALL_TODO_FAILURE = "FETCH_ALL_TODO_FAILURE";

export const FETCH_DETAIL_TODO = "FETCH_DETAIL_TODO";
export const FETCH_DETAIL_TODO_SUCCESS = "FETCH_DETAIL_TODO_SUCCESS";
export const FETCH_DETAIL_TODO_FAILURE = "FETCH_DETAIL_TODO_FAILURE";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";

export const FILTER_TODO = "FILTER_TODO";
export const FILTER_TODO_SUCCESS = "FILTER_TODO_SUCCESS";
export const FILTER_TODO_FAILURE = "FILTER_TODO_FAILURE";

export const UPDATE_STATUS_TODO = "UPDATE_STATUS_TODO";
export const UPDATE_STATUS_TODO_SUCCESS = "UPDATE_STATUS_TODO_SUCCESS";
export const UPDATE_STATUS_TODO_FAILURE = "UPDATE_STATUS_TODO_FAILURE";
